# Generated by Django 5.1 on 2024-09-15 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked_by',
        ),
    ]
