# Generated by Django 5.1 on 2024-09-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'male'), ('f', 'Female'), ('f', 'Other')], max_length=10),
        ),
    ]
